apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiaap-otel-collector.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "aiaap-otel-collector.fullname" . }}
